name: swift_elearning
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  google_fonts:
  http:
  cupertino_icons: ^1.0.2
  video_player: ^2.6.1
  flutter_dotenv: ^5.1.0
  image_picker: ^0.8.8
  http_parser: ^4.0.2
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\image\intro (1).png
    - assets\image\intro (2).png
    - assets\image\intro (3).png
    - assets\image\SWIFT welcome.png
    - assets\image\profile_picture.jpeg
    - assets\image\kuantitatif.jpeg
    - assets\image\kuantitatif.jpeg
    - assets\image\Penalaran_MTK.jpeg
    - assets\image\Penalaran_Umum.jpeg
    - assets\image\Literasi_Indo.jpeg
    - assets\image\Literasi_Inggris.jpeg
    - assets\image\KMBDM.jpeg
    - .env
