# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build APK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 16
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 16
          distribution: temurin

      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          
      - run: flutter pub get
      
      - run: flutter build apk --debug --split-per-abi

      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
      
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          tag: ${{ steps.extract_tag.outputs.tag_name }}
          artifacts: "build/app/outputs/apk/debug/*.apk"


